- name: Mechanical Keyboard RGB
  price: 99.99
  manufacturer: Logitech
  category: Keyboards

- name: Wireless Ergonomic Mouse
  price: 49.50
  manufacturer: Microsoft
  category: Mice

- name: Gaming Mousepad XXL
  price: 29.99
  manufacturer: Razer
  category: Accessories

- name: USB-C Hub 7-in-1
  price: 39.95
  manufacturer: Anker
  category: Accessories

- name: Wireless Mechanical Keyboard
  price: 120.00
  manufacturer: Corsair
  category: Keyboards

- name: Bluetooth Mouse Slim
  price: 25.99
  manufacturer: Apple
  category: Mice

- name: Webcam HD 1080p
  price: 65.00
  manufacturer: Logitech
  category: Webcams

- name: Noise-Canceling Headset
  price: 89.99
  manufacturer: HyperX
  category: Audio

- name: External SSD 1TB
  price: 149.99
  manufacturer: Samsung
  category: Storage

- name: Monitor Stand Adjustable
  price: 59.95
  manufacturer: Dell
  category: Accessories
